# Numpy
- 'Num'erical 'Py'thon
- Python에서 벡터, 행렬 등 수치 연산을 수행하는 선형대수 라이브러리
- 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공
- 데이터분석을 할 때 사용되는 라이브러리인 pandas와 matplotlib의 기반으로 사용
- 기본적으로 array(행렬) 단위로 데이터를 관리하며 이에 대해 연산을 수행함

In [ ]:
#!pip install numpy
import numpy as np

---

## 1. Array 정의 및 사용

In [ ]:
list1 = [1, 2, 3, 4, 5]
list1

[1, 2, 3, 4, 5]

In [ ]:
list2 = [1, 2, 3.5, 4, 5]
list2

[1, 2, 3.5, 4, 5]

In [ ]:
# 파이썬의 리스트를 np.array()를 이용하여 사용할 수 있음
array1 = np.array(list1)
array1

array([1, 2, 3, 4, 5])

In [ ]:
# 직접 리스트를 넣어서도 배열 생성 가능
array2 = np.array([1, 2, 3.5, 4, 5])
array2

array([1. , 2. , 3.5, 4. , 5. ])

In [ ]:
#n차원 배열을 만들 수 있음
array3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
array3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
list4 = [[[1,2],[3,4],[5,6]],[[5,6],[7,8],[9,10]]]
list4

[[[1, 2], [3, 4], [5, 6]], [[5, 6], [7, 8], [9, 10]]]

In [ ]:
array4 = np.array(list4)
array4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

#### shape/dim/size

In [ ]:
# .dim를 통해 배열의 차원수 반환
# .size를 통해 원소의 개수를 알 수 있음
print(array1.shape)
print(array1.ndim)
print(array1.size)

(5,)
1
5


In [ ]:
print(array3.shape)
print(array3.ndim)
print(array3.size)

(4, 3)
2
12


In [ ]:
print(array4.shape)
print(array4.ndim)
print(array4.size)

(2, 3, 2)
3
12


#### dtype

In [ ]:
# .dtype를 통해 자료형을 알 수 있음 
# array는 모든 원소가 같은 자료형을 가짐
print(array1.dtype)
print(array2.dtype)
print(array3.dtype)

int64
float64
int64


In [ ]:
array3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]], dtype="float")
array3

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
print(array3.dtype)

float64


In [ ]:
array3 = array3.astype(int)

### Q) array1과 array3의 차원 수는?

- array1.shape : (5,)
- array3.shape : (4, 3)<br>
<p>넘파이에서는 각 차원을 '축(axis)', 축의 개수를 '랭크(rank)'라고 부름.<br>
shape는 각 축(=차원)의 크기(또는 길이)를 의미.<br>
즉, array3은 3x5의 행렬로, 두 개의 랭크를 갖고, 각 축의 shape(크기)는 3, 5가 되는 것!<p>

### numpy에서 사용되는 자료형
(자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미)

- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8 ,16, 32, 54)
- 실수 float(16, 32, 64, 128)
-  complex(64, 128, 256)
- 불리언 bool
- 문자열 string
- 파이썬 오프젝트 object
- 유니코드 unicode

#### zeros

In [ ]:
# zeros는 입력받는 형태만큼 인자가 0으로 채워진 행렬을 만든다
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### ones

In [ ]:
# ones는 입력받는 형태만큼 인자가 1으로 채워진 행렬을 만든다
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### arange

In [ ]:
# arange는 파이썬 range와 비슷한 개념
# 한자리수(n)만 입력하면 0부터 n-1까지 1씩 늘어남
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 두개의 숫자(first, end)를 입력하면 first부터 end-1까지 1씩 늘어남
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 3번째 자리에 늘어나는 간격을 설정하여 사용 가능
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

#### reshape - 재배열

reshape(행 수, 열 수)

In [ ]:
array = np.arange(8)
array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
array_reshaped = array.reshape(2, 4)
array_reshaped

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#### reshape(-1) : 원래 배열의 길이와 남은 차원으로부터 추정

In [ ]:
array_reshaped2 = array.reshape(4, -1)
array_reshaped2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
array_reshaped3 = array.reshape(-1,4)
array_reshaped3

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
array4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

In [ ]:
array4.reshape(2,-1,-1)

ValueError: ignored

In [ ]:
array4_reshaped = array4.reshape(2,2,-1)
array4_reshaped

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]])

---

## 2. Array 연산

#### !  원칙적으로 shape가 같아야 연산 가능 !

각 array의 <font color=blue>같은 자리</font>에 있는 값들끼리 연산하기 때문이다.

In [ ]:
print(list1)
print(list2)

[1, 2, 3, 4, 5]
[1, 2, 3.5, 4, 5]


In [ ]:
list1*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
array1 *2

array([ 2,  4,  6,  8, 10])

In [ ]:
array1_ = np.array([[1,2,3],[4,5,6]])
array1_

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array2_ = np.array([[10,11,12],[13,14,15]])
array2_

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
print(array2_.shape)
print(array2_.shape)

(2, 3)
(2, 3)


#### 평균 구하기

In [ ]:
np.mean(array1_)

3.5

#### 덧셈

In [ ]:
list1 + list2

[1, 2, 3, 4, 5, 1, 2, 3.5, 4, 5]

In [ ]:
array1_ + array2_

array([[11, 13, 15],
       [17, 19, 21]])

In [ ]:
np.add(array1_ ,array2_)

array([[11, 13, 15],
       [17, 19, 21]])

#### 뺄셈

In [ ]:
array1_ - array2_

array([[-9, -9, -9],
       [-9, -9, -9]])

In [ ]:
np.subtract(array1_, array2_)

array([[-9, -9, -9],
       [-9, -9, -9]])

#### 곱셈

In [ ]:
array1_ * array2_

array([[10, 22, 36],
       [52, 70, 90]])

In [ ]:
np.multiply(array1_, array2_)

array([[10, 22, 36],
       [52, 70, 90]])

##### 참고 : 생각하고 계신 행렬의 곱(내적곱)을 하려면 .dot 이용
- (2, 3) * (3, 4) : 가능 
- (2, 3) * (2, 3) : 불가능 

In [ ]:
a = np.arange(1, 11)
b = np.arange(11, 21)
print(a * b)
print(a.dot(b))

[ 11  24  39  56  75  96 119 144 171 200]
935


#### 나눗셈

In [ ]:
array1_ / array2_

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [ ]:
np.divide(array1_ , array2_)

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

---

In [ ]:
np.maximum(array1_, array2_)

array([[10, 11, 12],
       [13, 14, 15]])

#### ! 원칙적으로 shape가 같아야 연산 가능하지만 브로드캐스팅이 가능하다!
- 넘파이에서 브로드캐스팅이란 서로 크기가 다른 array가 연산이 가능하게 하는 것


In [ ]:
array1_

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array1_.shape

(2, 3)

In [ ]:
array3_ = np.array([10, 11, 12])
array3_

array([10, 11, 12])

In [ ]:
array3_.shape

(3,)

#### 연산

In [ ]:
array1_ + array3_

array([[11, 13, 15],
       [14, 16, 18]])

In [ ]:
array1_ * array3_

array([[10, 22, 36],
       [40, 55, 72]])

In [ ]:
# 스칼라와도 가능
array1_ * 10

array([[10, 20, 30],
       [40, 50, 60]])

---

## 3. Array 인덱싱

#### 1차원 데이터 인덱싱

In [ ]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 0번째 요소
arr1[0]

0

In [ ]:
# 3번째 요소
arr1[3]

3

In [ ]:
#마지막 요소
print(arr1[-1])
print(arr1[len(arr1)-1])

9
9


In [ ]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [ ]:
print(arr1[3:])
print(arr1[:-2])
print(arr1[:])

[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 8 9]


#### 2차원 데이터 인덱싱

In [ ]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 2차원의 array를 인덱싱을 하기 위해선 2개의 인자 입력
# [행#, 열#]
print(arr2[0,0])
print(arr2[0][0])

1
1


In [ ]:
# 2번째 array의 전체 불러오기
arr2[2,:]

array([ 9, 10, 11, 12])

In [ ]:
# 2번째 array의 3번째 값 불러오기
arr2[2,3]

12

In [ ]:
# 모든 array의 3번째 값들만 불러오기
arr2[:,3]

array([ 4,  8, 12])

In [ ]:
arr2[[0,2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
arr2[[0,2],-1]

array([ 4, 12])

#### boolean을 이용한 인덱싱

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# boolean으로 확인하기

arr1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
# 조건에 맞는 (= 필터링된) 값 불러오기

arr1[arr1 > 5]

array([6, 7, 8, 9])

In [ ]:
# 조건에 맞는 값들의 인덱스값만 반환
np.where(arr1 > 5)

(array([6, 7, 8, 9]),)

In [ ]:
np.where(arr1 > 5, 'O', 'X') 

array(['X', 'X', 'X', 'X', 'X', 'X', 'O', 'O', 'O', 'O'], dtype='<U1')

---

## 4. 자주 쓰이는 Numpy 함수

#### concatenate - 결합
(주의: 가로, 세로 결합에 따라 row, column 갯수가 맞아야 결합이 가능)

In [ ]:
array1_

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array2_

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
# default axis = 0, 수평축
# 행을 기준으로 결합한다고 생각하면 쉬움
array_concat = np.concatenate((array1_, array2_))
print(array_concat)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]


In [ ]:
# axis=1로 하면 수직축
# 열을 기준으로 결합
array_con1 = np.concatenate((array1_, array2_), axis=1)
print(array_con1)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]]


#### split_분할

In [ ]:
array= np.split(array_concat,2) 
array

[array([[1, 2, 3],
        [4, 5, 6]]), array([[10, 11, 12],
        [13, 14, 15]])]

In [ ]:
array1, array2 = np.split(array_concat,2) 
print(array1)
print(array2)

[[1 2 3]
 [4 5 6]]
[[10 11 12]
 [13 14 15]]


### 이외에도 여러 함수 사용 가능
- .sum, .cumsum, .gradient
- 삼각함수 가능 .cos, .tanh 등등
- append, insert, delete 등을 통해 배열 변경 가능
- sort를 이용해 배열 정렬 가능
